#INCLUDE <P16F877A.INC> ; MICROCONTROLADOR UTILIZADO

__CONFIG _BOREN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _XT_OSC ;CONFIGURAÇÃO DOS FUSIVEIS

#DEFINE BANK0 BCF STATUS,RP0 ; SETA BANK 0 DE MEMORIA
#DEFINE BANK1 BSF STATUS,RP0 ; SETA BANK 1 DE MEMORIA
 
 	CBLOCK 0X20
		W_TEMP
		STATUS_TEMP
		TEMPO1 ;DELAY
		TEMPO2 ;DELAY
		REG
		PWMH
		PWML
		VAR1
		VAR2
		TEMPO3
		TEMPO4
		UNIDADE
		DEZENA
		CENTENA
	ENDC
 
ORG     0X00 ;ENDEREÇO INICIAL DE PROCESSAMENTO
GOTO	CONFIGURA
 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; CONFIGURAÇÃO DOS PORTS DO MICROCONTROLADOR
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

CONFIGURA

CLRF 	PORTA
CLRF 	PORTB
CLRF 	PORTC   	   ; GARANTE TODAS AS SAIDAS EM ZERO
CLRF 	PORTD
CLRF 	PORTE
 
BANK1				   ; ALTERA PARA BANCO 1
MOVLW	B'11011111'    ; CONFIGURA I/O DO PORTA
MOVWF	TRISA 
MOVLW	B'00001111'    ; CONFIGURA I/O DO PORTB
MOVWF	TRISB 
MOVLW	B'11111001'    ; CONFIGURA I/O DO PORTC
MOVWF	TRISC 
MOVLW	B'00000000'    ; CONFIGURA I/O DO PORTD
MOVWF	TRISD 
MOVLW	B'00000000'    ; CONFIGURA I/O DO PORTE
MOVWF	TRISE 
MOVLW 	B'10000111'    ; CONFIGURA OPTION REG
MOVWF 	OPTION_REG
MOVLW 	B'00000000'    ; CONFIGURA INTCON
MOVWF 	INTCON
;MOVLW 	B'00000111'    ; CONFIGURA ADCON1
;MOVWF 	ADCON1 
MOVLW 	B'00000111'    ; CONFIGURA CMCON
MOVWF 	CMCON
BANK0  

;INICIALIZAÇÃO DO PWM 

MOVLW	B'00001111'
MOVWF 	CCP1CON			; HABILITA PWM1
MOVWF  	CCP2CON  		; HOBILITA PWM2
CLRF 	CCPR1L  		; ZERA O PWM1 0%
CLRF 	CCPR2L  		; ZERA O PWM2 0%
BANK1			 		; BANCO1
MOVLW  	0XFF
MOVWF  	PR2   			; RESOLUÇÃO DE 10 BITS
BANK0					; BANCO0
BSF		T2CON,TMR2ON 	; TIMER2 LIGADO

;CONFIGURAÇÃO CONVERSOR AD

MOVLW	B'01000001'			
MOVWF	ADCON0			; AD LIGADO
BANK1
MOVWF	B'01000000'		; 
MOVLW	ADCON1
BANK0
GOTO  MAIN
 
 

;SUB-ROTINAS*********************************************************************************
 ;*********************************************************************************************
ATRASO_4MS
MOVLW .1
MOVWF TEMPO1
TEMPO_1
MOVLW .255
MOVWF TEMPO2
TEMPO_2
DECF TEMPO2,F
BTFSS STATUS,Z
 GOTO TEMPO_2
DECF TEMPO1,F
BTFSS STATUS,Z
GOTO TEMPO_1
RETURN
 
ATRASO_1S
MOVLW .255
MOVWF TEMPO3
TEMPO_3
MOVLW .255
MOVWF TEMPO4
TEMPO_4
DECF TEMPO4,F
BTFSS STATUS,Z
 GOTO TEMPO_4
DECF TEMPO3,F
BTFSS STATUS,Z
GOTO TEMPO_3
RETURN
 
 
ESCREVE_COMANDO   ;ENVIA COMANDO AO LCD
BCF  PORTE,0   ;SINAL DE COMANDO
NOP
MOVWF PORTD   ;INFORMAÇÃO NA PORTA D
NOP
 NOP
BSF  PORTE,1   ;PULSO DE ENABLE
NOP
NOP
BCF  PORTE,1
CALL ATRASO_4MS  ;ATRASO DE 1mS
RETURN
ESCREVE_DADO   ;ESCREVE CARACTERES NO LCD
BSF  PORTE,0
NOP
MOVWF PORTD   ;INFORMAÇÃO NA PORTA D
 NOP
NOP
BSF  PORTE,1   ;PULSO DE ENABLE
NOP
NOP
BCF  PORTE,1
CALL ATRASO_4MS  ;ATRASO 1mS
RETURN
;-------INICIALIZAÇÃO DO LCD----
INICIA_LCD
MOVLW 0X38
CALL ESCREVE_COMANDO
CALL ATRASO_1S
 MOVLW 0X38
CALL ESCREVE_COMANDO
MOVLW 0X0C
CALL ESCREVE_COMANDO
MOVLW 0X06
CALL ESCREVE_COMANDO
MOVLW 0X01
CALL ESCREVE_COMANDO
CALL ATRASO_1S
RETURN
;---------DECODIFICADOR LCD----
DECODIFICADOR
 ADDWF PCL,F ;PC<--PC+W
RETLW '0'  ;CODIGO ASCII
RETLW '1'
RETLW '2'
RETLW '3'
RETLW '4'
RETLW '5'
RETLW '6'
RETLW '7'
RETLW '8'
 RETLW '9'

;----------PORCENTAGEM-----------
PORCENTAGEM
INCF UNIDADE,F
MOVLW .10
SUBWF UNIDADE,W
BTFSS STATUS,Z
RETURN
MOVLW  .0
MOVWF UNIDADE
INCF DEZENA,F
MOVLW .10
SUBWF DEZENA,W
BTFSS STATUS,Z
RETURN
MOVLW  .0
MOVWF DEZENA
INCF CENTENA,F
MOVLW .1
SUBWF CENTENA,W
BTFSS STATUS,Z
RETURN
MOVLW .0
MOVWF UNIDADE
MOVWF DEZENA
MOVWF CENTENA
RETURN
 
 
 
;-------LIMITAR DE 0 ATE 9---------
 
MAIN
MOVLW 0X00
MOVWF REG
MOVLW 0X00
MOVWF VAR1
MOVLW 0X00
MOVWF VAR2
CALL ATRASO_4MS
CALL INICIA_LCD
VOLTA2
MOVLW 0X80
CALL ESCREVE_COMANDO
MOVLW 'T'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'M'
CALL ESCREVE_DADO
MOVLW 'P'
CALL ESCREVE_DADO
MOVLW ':'
CALL ESCREVE_DADO

;;;;COLETANDO UMA AMOSTRA
BSF  ADCON0,GO
BTFSC ADCON0,GO
GOTO $-1
BTFSC ADRESH,1
MOVLW '1'
BTFSS ADRESH,1
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESH,0
MOVLW '1'
BTFSS ADRESH,0
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,7
MOVLW '1'
BTFSS ADRESL,7
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,6
MOVLW '1'
BTFSS ADRESL,6
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,5
MOVLW '1'
BTFSS ADRESL,5
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,4
MOVLW '1'
BTFSS ADRESL,4
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,3
MOVLW '1'
BTFSS ADRESL,3
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,2
MOVLW '1'
BTFSS ADRESL,2
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,1
MOVLW '1'
BTFSS ADRESL,1
MOVLW '0'
CALL ESCREVE_DADO
BTFSC ADRESL,0
MOVLW '1'
BTFSS ADRESL,0
MOVLW '0'
CALL ESCREVE_DADO
;FAZER A LEITURA DE ADRESH(BANCO 0) E ADRESL(BANCO 1)

LOOP2
BTFSC PORTB,0  ;O BOTÃO 0 ESTÁ PRESSIONADO?
GOTO BOT2  ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO INCREMENTA
BOT2
BTFSC PORTB,1  ; BOTÃO 1 ESTÁ PRESSIONADO?
 GOTO BOT3  ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO DECREMENTA
BOT3
BTFSC PORTB,2  ;O BOTÃO 0 ESTÁ PRESSIONADO?
GOTO BOT4  ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO INCREMENTA_10
BOT4
BTFSC PORTB,3  ; BOTÃO 1 ESTÁ PRESSIONADO?
 GOTO VOLTA2  ;NÃO, ENTÃO TRATA BOTÃO LIBERADO
GOTO DECREMENTA_10
;;;;;;;;;;;;;;;;;;;INCREMENTA----------------------
INCREMENTA
MOVLW 0X01
CALL ESCREVE_COMANDO
CALL ATRASO_4MS
MOVLW 0XC0    ;CURSOR DO DISPLAY NA SEGUNDA LINHA
CALL ESCREVE_COMANDO
 MOVLW 'I'
CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'C'
CALL ESCREVE_DADO
MOVLW 'R'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'M'
 CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'T'
CALL ESCREVE_DADO
MOVLW 'A'
CALL ESCREVE_DADO

MOVF CCPR1L,W
MOVWF PWMH
 MOVLW .25
ADDWF PWMH,W
MOVWF CCPR1L 
;CALL ESCREVE_DADO
;INCF REG,F
;MOVF REG,W
;SUBLW .10
;BTFSC STATUS,Z
;CLRF REG
;MOVF REG,W
;CALL DECODIFICADOR
;CALL ESCREVE_DADO
CALL ATRASO_4MS
 GOTO    LOOP2
 
;;;;;;;;;;;;;;;DECREMENTA---------------------------------------
 
DECREMENTA
MOVLW 0X01
CALL ESCREVE_COMANDO
CALL ATRASO_4MS
MOVLW 0XC0    ;CURSOR DO DISPLAY NA SEGUNDA LINHA
CALL ESCREVE_COMANDO
MOVLW 'D'
CALL ESCREVE_DADO
 MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'C'
CALL ESCREVE_DADO
MOVLW 'R'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'M'
CALL ESCREVE_DADO
MOVLW 'E'
 CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'T'
CALL ESCREVE_DADO
MOVLW 'A'
CALL ESCREVE_DADO
MOVF CCPR2L,W
MOVWF PWMH
MOVLW .25
SUBWF PWMH,W
MOVWF CCPR2L 
;CALL ESCREVE_DADO
;INCF REG,F
;MOVF REG,W
;SUBLW .10
;BTFSC STATUS,Z
;CLRF REG
;MOVF REG,W
;CALL DECODIFICADOR
;CALL ESCREVE_DADO
CALL ATRASO_4MS
GOTO    LOOP2

;;;;;;;;;;;;;;;;;;;INCREMENTA  10  ----------------------
 
INCREMENTA_10
MOVLW 0X01
CALL ESCREVE_COMANDO
CALL ATRASO_4MS
MOVLW 0XC0
CALL ESCREVE_COMANDO
MOVLW 'I'
CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'C'
CALL ESCREVE_DADO
 MOVLW 'R'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'M'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'T'
 CALL ESCREVE_DADO
MOVLW 'A'
CALL ESCREVE_DADO
MOVLW '1'
CALL ESCREVE_DADO
MOVLW '0'
CALL ESCREVE_DADO
MOVLW .10
ADDWF VAR1,F
BTFSC STATUS,C
INCF VAR2,F
;COPIAR O RESULTADO PARA O REGISTRADOR BIT POR BIT
 
BTFSC VAR1,0
BSF  CCP1CON,4
BTFSS VAR1,0
BCF  CCP1CON,4
BTFSC VAR1,1
BSF  CCP1CON,5
BTFSS VAR1,1
BCF  CCP1CON,5
BTFSC VAR1,2
BSF  CCPR1L,0
BTFSS VAR1,2
BCF  CCPR1L,0
BTFSC VAR1,3
 BSF  CCPR1L,1
BTFSS VAR1,3
BCF  CCPR1L,1
BTFSC VAR1,4
BSF  CCPR1L,2
BTFSS VAR1,4
BCF  CCPR1L,2
BTFSC VAR1,5
BSF  CCPR1L,3
BTFSS VAR1,5
BCF  CCPR1L,3
BTFSC VAR1,6
BSF  CCPR1L,4
 BTFSS VAR1,6
BCF  CCPR1L,4
BTFSC VAR1,7
BSF  CCPR1L,5
BTFSS VAR1,7
BCF  CCPR1L,5
BTFSC VAR2,0
BSF  CCPR1L,6
BTFSS VAR2,0
BCF  CCPR1L,6
BTFSC VAR2,1
BSF  CCPR1L,7
BTFSS VAR2,1
 BCF  CCPR1L,7
CALL ATRASO_4MS
GOTO    LOOP2
 
;;;;;;;;;;;;;;;DECREMENTA   10---------------------------------------
 
DECREMENTA_10
MOVLW 0X01
CALL ESCREVE_COMANDO
CALL ATRASO_4MS
MOVLW 0XC0
CALL ESCREVE_COMANDO
 MOVLW 'D'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'C'
CALL ESCREVE_DADO
MOVLW 'R'
CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'M'
 CALL ESCREVE_DADO
MOVLW 'E'
CALL ESCREVE_DADO
MOVLW 'N'
CALL ESCREVE_DADO
MOVLW 'T'
CALL ESCREVE_DADO
MOVLW 'A'
CALL ESCREVE_DADO
MOVLW '1'
CALL ESCREVE_DADO
 MOVLW '0'
CALL ESCREVE_DADO
MOVLW .10
SUBWF VAR1,F
BTFSC STATUS,Z
DECF VAR2,F
;COPIAR O RESULTADO PARA O REGISTRADOR BIT POR BIT
BTFSC VAR1,0
BSF  CCP1CON,4
BTFSS VAR1,0
BCF  CCP1CON,4
 
BTFSC VAR1,1
BSF  CCP1CON,5
BTFSS VAR1,1
BCF  CCP1CON,5
BTFSC VAR1,2
BSF  CCPR1L,0
BTFSS VAR1,2
BCF  CCPR1L,0
BTFSC VAR1,3
BSF  CCPR1L,1
BTFSS VAR1,3
BCF  CCPR1L,1
BTFSC VAR1,4
 BSF  CCPR1L,2
BTFSS VAR1,4
BCF  CCPR1L,2
BTFSC VAR1,5
BSF  CCPR1L,3
BTFSS VAR1,5
BCF  CCPR1L,3
BTFSC VAR1,6
BSF  CCPR1L,4
BTFSS VAR1,6
BCF  CCPR1L,4
BTFSC VAR1,7
BSF  CCPR1L,5
 BTFSS VAR1,7
BCF  CCPR1L,5
BTFSC VAR2,0
BSF  CCPR1L,6
BTFSS VAR2,0
BCF  CCPR1L,6
BTFSC VAR2,1
BSF  CCPR1L,7
BTFSS VAR2,1
BCF  CCPR1L,7
CALL ATRASO_4MS
GOTO    LOOP2
 
 END

;RC2 COOLER
;RC1 RESISTOR
